Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Proyecto.Models;

namespace Proyecto.Controllers
{
    public class AlumnoController : Controller
    {
        private EscuelaContext _context;
        public AlumnoController(EscuelaContext context)
        {
            _context = context;
        }

        private List<SelectListItem> ObtenerListaDeCursosParaDropDownList()
        {
            var idCursos = from ids in _context.Cursos select ids;
            
            List<SelectListItem> listIdCursos = new List<SelectListItem>();
            foreach (var id in idCursos)
            {
                listIdCursos.Add(new SelectListItem(){Text = id.Nombre, Value = id.Id});
            }

            return listIdCursos;
        }
        public IActionResult Index(string id)
        {
            if(!string.IsNullOrEmpty(id))
            {
                var alumno = from alum in _context.Alumnos
                                where alum.Id == id
                                select alum;

                return View(alumno.SingleOrDefault());
            }else
            {
                return View("MultiAlumno",_context.Alumnos);
            }
        }
        
        public IActionResult Create()
        {
            ViewBag.fecha = DateTime.Now;
            
            ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();

            return View();
        }

        [HttpPost]
        public IActionResult Create(Alumno alumno)
        {
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                try
                {
                    var curso = _context.Cursos.Find(alumno.CursoId);

                    alumno.CursoId = curso.Id;

                    _context.Alumnos.Add(alumno);
                    _context.SaveChanges();

                    ViewBag.MensajeExtra = "Alumno Creado";
                    return View("Index", alumno);
                }catch(Exception ex){
                    ViewBag.MensajeException = ex.Message;
                    ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                    return View(alumno);
                }
            }
            else
            {
                ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                return View(alumno);
            }
        }

        public IActionResult Update(Alumno alumno)
        {
            ViewBag.IdAlumnoAEditar = alumno.Id;
            ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
            ViewBag.fecha = DateTime.Now;

            return View();
        }

        [HttpPost]
        public IActionResult Update(Alumno alumno, bool flag = false)
        {
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                try
                {
                    var curso = _context.Cursos.Find(alumno.CursoId);

                    alumno.CursoId = curso.Id;

                    _context.Alumnos.Update(alumno);
                    _context.SaveChanges();

                    ViewBag.MensajeExtra = "Alumno Actualizado";
                    return View("Index", alumno);
                }catch(Exception ex){
                    ViewBag.MensajeException = ex.Message;
                    ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                    return View(alumno);
                }
            }
            else
            {
                ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                return View(alumno);
            }
        }

        public IActionResult Delete(Alumno alumno)
        {
            ViewBag.IdAlumnoAEliminar = alumno.Id;
            ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
            ViewBag.fecha = DateTime.Now;

            return View();
        }

        [HttpPost]
        public IActionResult Delete(Alumno alumno, bool flag = false)
        {
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                try
                {
                    //var curso = _context.Cursos.Find(alumno.CursoId);

                    //alumno.CursoId = curso.Id;

                    _context.Alumnos.Remove(alumno);
                    _context.SaveChanges();

                    ViewBag.MensajeExtra = "Alumno Eliminado";
                    return View("MultiAlumno", _context.Alumnos);
                }catch(Exception ex){
                    ViewBag.MensajeException = ex.Message;
                    ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                    return View(alumno);
                }
            }
            else
            {
                ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                return View(alumno);
            }

        }
        public IActionResult MultiAlumno()
        {
            // var asignatura = new Asignatura{
            //     UniqueId = Guid.NewGuid().ToString(),
            //     Nombre = "Programación"
            // };

            //List<Alumno> listaAlumnos = GenerarAlumnosAlAzar();

            ViewBag.cosaDinamica = "PulpFiction";
            ViewBag.fecha = DateTime.Now;

            //asldkjals
            
            return View("MultiAlumno",_context.Alumnos);
        }
    }
}

Controllers/AsignaturaController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Proyecto.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Proyecto.Controllers
{
    public class AsignaturaController : Controller
    {
        private EscuelaContext _context;
        public AsignaturaController(EscuelaContext context)
        {
            _context = context;
        }

        // public IActionResult Index()
        // {
        //     //return View( new Asignatura{Nombre = "Programación", Id = Guid.NewGuid().ToString()} );

        //     return View(_context.Asignaturas.FirstOrDefault());
        // }

        private List<SelectListItem> ObtenerListaDeCursosParaDropDownList()
        {
            var idCursos = from ids in _context.Cursos select ids;
            
            List<SelectListItem> listIdCursos = new List<SelectListItem>();
            foreach (var id in idCursos)
            {
                listIdCursos.Add(new SelectListItem(){Text = id.Nombre, Value = id.Id});
            }

            return listIdCursos;
        }

        [Route("Asignatura/Index")]
        [Route("Asignatura/Index/{asignaturaId}")]
        public IActionResult Index(string asignaturaId)
        {
            if(!string.IsNullOrEmpty(asignaturaId))
            {
                var asignatura = from asig in _context.Asignaturas
                                where asig.Id == asignaturaId
                                select asig;

                return View(asignatura.SingleOrDefault());
            }else
            {
                return View("MultiAsignatura",_context.Asignaturas);
            }
        }
        
        public IActionResult Create()
        {
            ViewBag.fecha = DateTime.Now;
            
            ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();

            return View();
        }

        [HttpPost]
        public IActionResult Create(Asignatura asignatura)
        {
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                try
                {
                    var curso = _context.Cursos.Find(asignatura.CursoId);

                    asignatura.CursoId = curso.Id;

                    _context.Asignaturas.Add(asignatura);
                    _context.SaveChanges();

                    ViewBag.MensajeExtra = "Asignatura Creado";
                    return View("Index", asignatura);
                }catch(Exception ex){
                    ViewBag.MensajeException = ex.Message;
                    ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                    return View(asignatura);
                }
            }
            else
            {
                ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                return View(asignatura);
            }
        }

        public IActionResult Update(Asignatura asignatura)
        {
            ViewBag.IdAsignaturaAEditar = asignatura.Id;
            ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
            ViewBag.fecha = DateTime.Now;

            return View();
        }

        [HttpPost]
        public IActionResult Update(Asignatura asignatura, bool flag = false)
        {
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                try
                {
                    var curso = _context.Cursos.Find(asignatura.CursoId);

                    asignatura.CursoId = curso.Id;

                    _context.Asignaturas.Update(asignatura);
                    _context.SaveChanges();

                    ViewBag.MensajeExtra = "Asignatura Actualizado";
                    return View("Index", asignatura);
                }catch(Exception ex){
                    ViewBag.MensajeException = ex.Message;
                    ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                    return View(asignatura);
                }
            }
            else
            {
                ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                return View(asignatura);
            }
        }
        public IActionResult Delete(Asignatura asignatura)
        {
            ViewBag.IdAsignaturaAEliminar = asignatura.Id;
            ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
            ViewBag.fecha = DateTime.Now;

            return View();
        }

        [HttpPost]
        public IActionResult Delete(Asignatura asignatura, bool flag = false)
        {
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                try
                {
                    //var curso = _context.Cursos.Find(alumno.CursoId);

                    //alumno.CursoId = curso.Id;

                    _context.Asignaturas.Remove(asignatura);
                    _context.SaveChanges();

                    ViewBag.MensajeExtra = "Asignatura Eliminado";
                    return View("MultiAsignatura", _context.Asignaturas);
                }catch(Exception ex){
                    ViewBag.MensajeException = ex.Message;
                    ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                    return View(asignatura);
                }
            }
            else
            {
                ViewBag.idCursosDisponibles = ObtenerListaDeCursosParaDropDownList();
                return View(asignatura);
            }

        }
        public IActionResult MultiAsignatura()
        {
            ViewBag.cosaDinamica = "PulpFiction";
            ViewBag.fecha = DateTime.Now;
            
            return View("MultiAsignatura",_context.Asignaturas);
        }
    }
}

Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Proyecto.Models;

namespace Proyecto.Controllers
{
    public class CursoController : Controller
    {
        private EscuelaContext _context;
        public CursoController(EscuelaContext context)
        {
            _context = context;
        }

        public IActionResult Index(string id)
        {
            if(!string.IsNullOrEmpty(id))
            {
                var curso = from cur in _context.Cursos
                                where cur.Id == id
                                select cur;

                return View(curso.SingleOrDefault());
            }else
            {
                return View("MultiCurso",_context.Cursos);
            }
        }

        public IActionResult Create()
        {
            ViewBag.fecha = DateTime.Now;

            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Curso curso)
        {
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                var escuela = _context.Escuelas.FirstOrDefault();

                curso.EscuelaId = escuela.Id;

                _context.Cursos.Add(curso);
                _context.SaveChanges();
                
                ViewBag.MensajeExtra = "Curso Creado";
                return View("Index", curso);
            }
            else
            {
                return View(curso);
            }
            
        }

        public IActionResult Update(Curso curso)
        {
            ViewBag.IdCursoAEditar = curso.Id;
            ViewBag.fecha = DateTime.Now;

            return View();
        }

        [HttpPost]
        public IActionResult Update(Curso curso, bool flag = false)
        {
            ViewBag.IdCursoAEditar = curso.Id;
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                var escuela = _context.Escuelas.FirstOrDefault();

                curso.EscuelaId = escuela.Id;

                _context.Cursos.Update(curso);
                _context.SaveChanges();
                
                ViewBag.MensajeExtra = "Curso Actualizado";
                return View("Index", curso);
            }
            else
            {
                return View(curso);
            }
        }

        public IActionResult Delete(Curso curso)
        {
            ViewBag.IdCursoAEliminar = curso.Id;
            ViewBag.fecha = DateTime.Now;

            return View();
        }
        
        [HttpPost]
        public IActionResult Delete(Curso curso, bool flag = false)
        {
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                var escuela = _context.Escuelas.FirstOrDefault();

                curso.EscuelaId = escuela.Id;

                _context.Cursos.Remove(curso);
                _context.SaveChanges();
                
                ViewBag.MensajeExtra = "Curso Eliminado";
                //return View("Index", curso);
                return View("MultiCurso",_context.Cursos);
            }
            else
            {
                return View(curso);
            }
        }

        public IActionResult MultiCurso()
        {
            // var asignatura = new Asignatura{
            //     UniqueId = Guid.NewGuid().ToString(),
            //     Nombre = "Programación"
            // };

            //List<Alumno> listaAlumnos = GenerarAlumnosAlAzar();

            ViewBag.cosaDinamica = "PulpFiction";
            ViewBag.fecha = DateTime.Now;

            //asldkjals
            
            return View("MultiCurso",_context.Cursos);
        }
    }
}

Views/Shared/AsignaturaSimple.cshtml
@model Asignatura

<p>
    Nombre: @Model.Nombre </br>
    Id: @Model.UniqueId
</p>

Views/Shared/ListaObjetoEscuela.cshtml
@*
@model List<ObjetoEscuelaBase>*@

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Id</th>
            <!--<th scope="col">Jornada</th>
            <th scope="col">Direccion</th>-->
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td>@obj.Nombre</td>
                <td>@obj.Id</td>
                @{
                    if (obj is Curso)
                    {
                        <td>@Html.ActionLink("Actualizar", "Update", "Curso", new{Id = obj.Id, Nombre = obj.Nombre, Jornada = obj.Jornada, Direccion = obj.Direccion}, new{@class="btn btn-warning"})</td>
                        <td>@Html.ActionLink("Eliminar", "Delete", "Curso", new{Id = obj.Id, Nombre = obj.Nombre, Jornada = obj.Jornada, Direccion = obj.Direccion}, new{@class="btn btn-danger"})</td>
                    }
                    else if(obj is Alumno)
                    {
                        <td>@Html.ActionLink("Actualizar", "Update", "Alumno", new{Id = obj.Id, Nombre = obj.Nombre, CursoId = obj.CursoId}, new{@class="btn btn-warning"})</td>
                        <td>@Html.ActionLink("Eliminar", "Delete", "Alumno", new{Id = obj.Id, Nombre = obj.Nombre, CursoId = obj.CursoId}, new{@class="btn btn-danger"})</td>
                    }
                    else if(obj is Asignatura)
                    {
                        <td>@Html.ActionLink("Actualizar", "Update", "Asignatura", new{Id = obj.Id, Nombre = obj.Nombre, CursoId = obj.CursoId}, new{@class="btn btn-warning"})</td>
                        <td>@Html.ActionLink("Eliminar", "Delete", "Asignatura", new{Id = obj.Id, Nombre = obj.Nombre, CursoId = obj.CursoId}, new{@class="btn btn-danger"})</td>
                    }
                    else
                    {
                        <td>Actualizar</td>
                        <td>Eliminar</td>
                    }
                }
                
            </tr>
        }
    </tbody>
</table>

Views/Shared/ObjetoEscuelaSimple.cshtml
@model ObjetoEscuelaBase

<p>
    Nombre: @Model.Nombre </br>
    Id: @Model.Id
</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Proyecto</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            <i>Render Body...</i>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Proyecto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Simple.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - CoreEscuela</title>
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
    crossorigin="anonymous"> 
</head>
<body>
    @RenderBody()
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" 
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" 
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" 
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" 
        crossorigin="anonymous"></script>
    <!--<environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>-->
</body>
</html>