Models/Curso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Proyecto.Models
{
    public class Curso : ObjetoEscuelaBase
    {
        //override
        [Display(Prompt ="Menor o igual a 5")]
        [Required(ErrorMessage = "El nombre del curso es requerido") ]
        [StringLength(5, ErrorMessage ="El nombre del curso no puede ser mayor a 5 caracteres")]
        public override string Nombre {get; set;}
   
        //referencia hacia padre
        public string EscuelaId { get; set; }
        public Escuela Escuela { get; set; }

        //propiedad normal
        public TiposJornada Jornada { get; set; }
        
        [Display(Prompt ="Dirección de correspondencia", Name ="Address")]
        [Required(ErrorMessage = "Se requiere incluir una dirección")]
        [MinLength(10, ErrorMessage = "La longitud minima de la dirección es 10 caracteres")]
        public string Direccion { get; set; }
        
        //referencia hacia hijos
        public List<Asignatura> Asignaturas {get; set;}
        public List<Alumno> Alumnos {get; set;}

    }
}

Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Proyecto.Models;

namespace Proyecto.Controllers
{
    public class CursoController : Controller
    {
        private EscuelaContext _context;
        public CursoController(EscuelaContext context)
        {
            _context = context;
        }

        public IActionResult Index(string id)
        {
            if(!string.IsNullOrEmpty(id))
            {
                var curso = from cur in _context.Cursos
                                where cur.Id == id
                                select cur;

                return View(curso.SingleOrDefault());
            }else
            {
                return View("MultiCurso",_context.Cursos);
            }
        }

        public IActionResult Create()
        {
            ViewBag.fecha = DateTime.Now;

            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Curso curso)
        {
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                var escuela = _context.Escuelas.FirstOrDefault();

                curso.EscuelaId = escuela.Id;

                _context.Cursos.Add(curso);
                _context.SaveChanges();
                
                ViewBag.MensajeExtra = "Curso Creado";
                return View("Index", curso);
            }
            else
            {
                return View(curso);
            }
            
        }

        public IActionResult Update(Curso curso)
        {
            ViewBag.IdCursoAEditar = curso.Id;
            ViewBag.fecha = DateTime.Now;

            return View();
        }

        [HttpPost]
        public IActionResult Update(Curso curso, bool flag = false)
        {
            ViewBag.IdCursoAEditar = curso.Id;
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                var escuela = _context.Escuelas.FirstOrDefault();

                curso.EscuelaId = escuela.Id;

                _context.Cursos.Update(curso);
                _context.SaveChanges();
                
                ViewBag.MensajeExtra = "Curso Actualizado";
                return View("Index", curso);
            }
            else
            {
                return View(curso);
            }
        }

        public IActionResult Delete(Curso curso)
        {
            ViewBag.IdCursoAEliminar = curso.Id;
            ViewBag.fecha = DateTime.Now;

            return View();
        }
        
        [HttpPost]
        public IActionResult Delete(Curso curso, bool flag = false)
        {
            ViewBag.fecha = DateTime.Now;
            if(ModelState.IsValid)
            {
                var escuela = _context.Escuelas.FirstOrDefault();

                curso.EscuelaId = escuela.Id;

                _context.Cursos.Remove(curso);
                _context.SaveChanges();
                
                ViewBag.MensajeExtra = "Curso Eliminado";
                //return View("Index", curso);
                return View("MultiCurso",_context.Cursos);
            }
            else
            {
                return View(curso);
            }
        }

        public IActionResult MultiCurso()
        {
            // var asignatura = new Asignatura{
            //     UniqueId = Guid.NewGuid().ToString(),
            //     Nombre = "Programación"
            // };

            //List<Alumno> listaAlumnos = GenerarAlumnosAlAzar();

            ViewBag.cosaDinamica = "PulpFiction";
            ViewBag.fecha = DateTime.Now;

            //asldkjals
            
            return View("MultiCurso",_context.Cursos);
        }
    }
}

Controllers/EscuelaController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Proyecto.Models;

namespace Proyecto.Controllers
{

    public class EscuelaController : Controller
    {
        private EscuelaContext _context;
        public EscuelaController(EscuelaContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.cosaDinamica = "Pulp Fiction";
            
            var escuela = _context.Escuelas.FirstOrDefault();

            return View(escuela);
        }
    }
}

Views/Curso/Create.cshtml
@model Curso


@{
    ViewData["Title"] = "Creación de Curso";
    Layout = "_Simple";
}

<h1>@ViewData["Title"]</h1>

<!--<div asp-validation-summary="All"></div>-->
<form method="POST">
    <div>
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre"/>
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>  
    <div>
        <label asp-for="Direccion"></label>
        <input asp-for="Direccion"/>
        <span asp-validation-for="Direccion" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Jornada"></label>
        @Html.DropDownList(
            "Jornada",
            Html.GetEnumSelectList<TiposJornada>(),
            "Seleccione una jornada",
            new { @class = "form-control" }
        )
        <span asp-validation-for="Jornada" class="text-danger"></span>
    </div>
    <input type="submit" value="Crear" class="btn btn-success"/>
    @Html.ActionLink("Cancelar", "Multicurso", "Curso",null, new{@class="btn btn-primary"})
</form>


<p><strong>@ViewData["fecha"]</strong></p>

Views/Curso/Delete.cshtml
@model Curso


@{
    ViewData["Title"] = "Eliminar Curso";
    Layout = "_Simple";
}

<h1>@ViewData["Title"]</h1>
<h2>@ViewBag.IdCursoAEliminar</h2>

<div asp-validation-summary="All"></div>
<form method="POST">
    <div>
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" disabled/>
    </div>  
    <div>
        <label asp-for="Direccion"></label>
        <input asp-for="Direccion" disabled/>
    </div>
    <div>
        <label asp-for="Jornada"></label>
        <input asp-for="Jornada" disabled/>
    </div>
    <input type="submit" value="Confirmar para Eliminar" class="btn btn-danger"/>
    @Html.ActionLink("Cancelar", "Multicurso", "Curso",null, new{@class="btn btn-primary"})
</form>


<p><strong>@ViewData["fecha"]</strong></p>

Views/Curso/Index.cshtml
@model Curso


@{
    ViewData["Title"] = "Información Curso";
    Layout = "_Simple";
}

<h1>@ViewData["Title"]</h1>
<h2>@ViewBag.MensajeExtra</h2>

<strong>Desde la vista normal</strong>
<p>
    Nombre: @Model.Nombre </br>
    Id: @Model.Id
</p>

<strong>Desde la vista parcial</strong>
<partial name="ObjetoEscuelaSimple"/>

@Html.ActionLink("Regresar", "Multicurso", "Curso",null, new{@class="btn btn-primary"})

<p><strong>@ViewBag.cosaDinamica</strong></p>
<p><strong>@ViewData["fecha"]</strong></p>

Views/Curso/MultiCurso.cshtml
@model IEnumerable<Curso>

@{
    ViewData["Title"] = "Información Curso";
    Layout = "_Simple";
}

<h1>@ViewData["Title"]</h1>

<strong>Desde la vista parcial - Utilizando Tabla de Botstrap</strong>
@Html.ActionLink("Crear", "Create", "Curso",null, new{@class="btn btn-success"})
@Html.ActionLink("Ir a Escuela", "Index", "Escuela",null, new{@class="btn btn-info"})
<partial name="ListaObjetoEscuela" />

<p><strong>@ViewBag.cosaDinamica</strong></p>
<p><strong>@ViewData["fecha"]</strong></p>

Views/Curso/Update.cshtml
@model Curso


@{
    ViewData["Title"] = "Actualización de Curso";
    Layout = "_Simple";
}

<h1>@ViewData["Title"]</h1>
<h2 class="" style="color:red">@ViewBag.MensajeException</h2>
<h2>@ViewBag.IdCursoAEditar</h2>

<!--<div asp-validation-summary="All"></div>-->
<form method="POST">
    <div>
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre"/>
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>  
    <div>
        <label asp-for="Direccion"></label>
        <input asp-for="Direccion"/>
        <span asp-validation-for="Direccion" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Jornada"></label>
        <!--<input asp-for="Jornada"/>-->
        @Html.DropDownList(
            "Jornada",
            Html.GetEnumSelectList<TiposJornada>(),
            "Seleccione una jornada",
            new { @class = "form-control" }
        )
        <span asp-validation-for="Jornada" class="text-danger"></span>
    </div>
    <input type="submit" value="Actualizar" class="btn btn-warning"/>
    @Html.ActionLink("Cancelar", "Multicurso", "Curso",null, new{@class="btn btn-primary"})
</form>


<p><strong>@ViewData["fecha"]</strong></p>